sudo: required
dist: trusty
before_install: true
install: true
before_script:
  - cd "${TRAVIS_BUILD_DIR}/go"
  - export GO15VENDOREXPERIMENT=1
  - go get -u github.com/golang/dep/cmd/dep
script:
  - dep ensure -v
  - go test -timeout 30s ./...

matrix:
  include:
    - language: go
      go:
      - "1.10"
    - language: go
      go:
      - "1.11"
    - language: python
      python:
      - "2.7"
      before_script:
      - cd "${TRAVIS_BUILD_DIR}/py"
      script:
      - python main.py
    - language: python
      python:
      - "3.6"
      before_script:
      - cd "${TRAVIS_BUILD_DIR}/py"
      script:
      - python main.py
    - language: node_js
      node_js:
      - "9.3.0"
      before_script:
      - cd "${TRAVIS_BUILD_DIR}/js"
      - npm install -g yarn
      - yarn install
      script:
      - yarn test

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always